### PR TITLE
Rename `EventTarget#on()` to `EventTarget#when()`

### LINKED ISSUE #39: `on()` collides with all sorts of code in the wild.
Lots of libraries and runtimes use `on()` as a generic event handling mechanism. This name might cause problems for them updating and as such cause unnecessary friction. It would be good to see if there is another name that is less prevalent in the same design space that wouldn't collide with Cloudflare Workers, Bun, Node.js, etc. and the libraries written for them (Note: all of these have some form of EventTarget, but often mix with EventEmitter's `on` in the wild or for backwards compatibility).

### PR DESCRIPTION
**Pull request by domfarolino**
See https://github.com/WICG/observable/issues/39 for discussion, and https://chromium-review.googlesource.com/c/chromium/src/+/5730072 for WPTs that will be upstreamed shortly.

Closes #39.

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/161.html" title="Last updated on Aug 13, 2024, 10:38 AM UTC (6f33850)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/161/f954c91...6f33850.html" title="Last updated on Aug 13, 2024, 10:38 AM UTC (6f33850)">Diff</a>

### CODE REVIEW

**Review by zloirock — COMMENTED** [review]
Collision with promises `.then` could cause some problems - almost the same pronunciation when reading the code, 1 letter difference -> typos, etc.

**Comment by domfarolino** [comment]
We could go with `EventTarget#upon()`. But I still like `when()` a little better. I don't think `then()` and `when()` have the same pronunciation just because they rhyme.

**Comment by domfarolino** [comment]
Update, I've put an X poll out for this: https://x.com/domfarolino/status/1815458583334842691 to get a feel for how the community feels.

**Comment by tetsuharuohzeki** [comment]
> Update, I've put an X poll out for this: https://x.com/domfarolino/status/1815458583334842691 to get a feel for how the community feels.

I would like to vote `.listen()` in that reply.

**Comment by domfarolino** [comment]
Conversation about naming should be had in https://github.com/WICG/observable/issues/39.

**Review by keithamus — APPROVED** [review]
LGTM

**Comment by domfarolino** [comment]
Given the discussion in https://github.com/WICG/observable/issues/39#issuecomment-2253493300 and https://github.com/WICG/observable/issues/39#issuecomment-2253501551, and the general support for those comments I'm seeing, I'm comfortable moving forward with this PR. I'll merge this PR later today.

**Pull request merged**
